let grand = document.querySelector(".grandteszt");
console.log(grand);
grand.style.color = "red";
let szulo = document.querySelector(".szulo");
szulo.style.color = "green";
szulo.style.fontSize = "3rem";
console.log(szulo);
let child1 = document.querySelector(".child1");
console.log(child1);
child1.style.fontSize = "2rem";
let child2 = document.querySelector(".child2");
console.log(child2);
child2.style.fontWeight = "italic";
child2.style.color = "red";
